### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by msdmazarei** [msdmazarei/FrontEndAdminPanelStandard#3]
ILocalization cannot extends a class, generally Interface should extends another Interfaces not classes.
I thins fa, en constants should implements ILocalizations.

**Comment by hrkazemi** [comment]
LocalizedStringsMethods is an interface.
check [**react-localization**](https://github.com/stefalda/react-localization/blob/master/lib/LocalizedStrings.d.ts) declare module file.

**Comment by msdmazarei** [comment]
Thanks, what about fa,en which should implements ILocalications.

**Comment by hrkazemi** [comment]
fa, en, ... are just dictionary file.
**ILocalications** interface has all the method to get and set translation or change language in app.

this part:
```
const Localization: ILocalization = new LocalizedStrings({
    fa: fa,
    en: en
});
```
handle type checking for us.
