### ISSUE TITLE
messages

### ISSUE THREAD

**Issue by chimanSeyedhashemi** [msdmazarei/FrontEndAdminPanelStandard#4]
for every message we need a title, description and a title.
message Type = {
title : string,
description : string,
type : string(success/warning/error/info)
}

In Actions, access, request, client business ...
admin panel needs messages.

**Comment by hrkazemi** [comment]
@chimanchiman 
type of message ```success, warning, ...``` is part of **component business**, not message's dictionary.
for example:
```
user_x_access_y_removed: 'user {0} access {1} removed'.
```
in this case if *super admin* update (remove) the user's access then type should be **success**,
but if the user try to do some action with that access message will be toast in **error** type.

for the **title** part:
title is a text that should be translated, it can be added to message section or other part of dictionary.
like **type**, title could be different with the same message.
